import { beforeEach, describe, expect, it, vi } from 'vitest';
import { clearImageCache, getImages as resolveImages, normalizePexels } from '../server/images';
import { byId } from '../src/data/learning';
const makePhoto = (id: number) => ({ id, width: 900, height: 700, alt: 'Red apple fruit', photographer: 'Test fixture photographer', photographer_url: 'https://www.pexels.com/@fixture', url: `https://www.pexels.com/photo/${id}/`, src: { medium: `https://images.pexels.com/photos/${id}/medium.jpg`, large: `https://images.pexels.com/photos/${id}/large.jpg` } });
const sense = byId.get('苹果')!.senses[0].id;
// Isolate legacy Pexels behavior behind an explicitly empty Openverse fallback.
const getImages: typeof resolveImages = (word, sense, opts = {}) => resolveImages(word, sense, { ...opts, fetcher: (url, init) => String(url).startsWith('https://api.openverse.org/') ? Promise.resolve(new Response(JSON.stringify({ results: [] }))) : (opts.fetcher ?? fetch)(url, init) });
beforeEach(clearImageCache);
describe('image provider boundary', () => {
  it('honestly reports a missing key with a real local fallback', async () => { const result = await getImages('苹果', sense); expect(result.status).toBe('curated'); expect(result.message).toContain('curated'); expect(result.images[0].thumbnailUrl).toBe('/photos/apple.jpg'); });
  it('does not fetch arbitrary words or arbitrary image queries', async () => { await expect(getImages('unknown', sense)).rejects.toThrow('known dictionary'); await expect(getImages('苹果', 'wrong')).rejects.toThrow('known dictionary'); });
  it('returns no photos for abstract words', async () => { const fetcher = vi.fn(); const result = await getImages('因为', 'sense-0', { pexelsKey: 'fixture', fetcher }); expect(result.images).toEqual([]); expect(fetcher).not.toHaveBeenCalled(); });
  it('normalizes, deduplicates and rejects tiny or unsafe URLs', () => { const images = normalizePexels([makePhoto(1), makePhoto(1), { ...makePhoto(2), width: 50 }, { ...makePhoto(3), src: { medium: 'javascript:alert(1)', large: 'https://evil.example/x' } }, makePhoto(4)], 'apple fruit'); expect(images.map(i => i.id)).toEqual(['pexels-1', 'pexels-4']); });
  it('returns 12 real provider responses with attribution', async () => { const fetcher = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ photos: Array.from({ length: 24 }, (_, i) => makePhoto(i)) }) }); const result = await getImages('苹果', sense, { pexelsKey: 'server-secret', fetcher }); expect(result.images).toHaveLength(12); expect(result.images[0].photographer).toBe('Test fixture photographer'); expect(fetcher.mock.calls[0][1].headers.Authorization).toBe('server-secret'); expect(result.status).toBe('live'); });
  it('prevents duplicate calls and reuses cached responses', async () => { const fetcher = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ photos: [makePhoto(1)] }) }); await Promise.all([getImages('苹果', sense, { pexelsKey: 'fixture', fetcher }), getImages('苹果', sense, { pexelsKey: 'fixture', fetcher })]); await getImages('苹果', sense, { pexelsKey: 'fixture', fetcher }); expect(fetcher).toHaveBeenCalledTimes(1); });
  it('handles failed providers without breaking dictionary data', async () => { const fetcher = vi.fn().mockRejectedValue(new Error('Network unavailable')); const result = await getImages('苹果', sense, { pexelsKey: 'fixture', fetcher }); expect(result.status).toBe('curated'); expect(result.message).toContain('unavailable'); expect(byId.get('苹果')!.pinyin).toBe('píng guǒ'); });
  it('handles empty provider results', async () => { const fetcher = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ photos: [] }) }); expect((await getImages('苹果', sense, { pexelsKey: 'fixture', fetcher })).message).toContain('No additional'); });
});
