import { ArrowRight, ArrowUpRight, AudioLines, BookOpen, Globe2, Sparkles } from 'lucide-react';
import { byId, categories, words } from '../data/learning';
import { localPhoto } from '../data/photos';
import type { Word } from '../types';
import { SearchBar } from '../components/SearchBar';
import { Photo } from '../components/Photo';
import { PronunciationButton } from '../components/PronunciationButton';
import { WordCard } from '../components/WordCard';
import { WordThumbnail } from '../components/WordThumbnail';
interface Props { onSearch: (q: string) => void; onOpen: (w: Word) => void; onCategory: (c: string) => void; recent: string[]; saved: string[]; onSave: (id: string) => void }
export function Home({ onSearch, onOpen, onCategory, recent, saved, onSave }: Props) {
  const popular = ['苹果', '猫', '飞机', '雨伞', '狗', '树'].map(id => byId.get(id)!);
  const day = Math.floor(Date.now() / 86_400_000); const dayWords = words.filter(w => w.photo && w.senses[0].examples.length); const today = dayWords[day % dayWords.length];
  return <>
    <section className="hero"><div className="hero-copy"><div className="hero-kicker"><span/> A LITTLE CURIOSITY. A WHOLE NEW LANGUAGE.</div><h1>Every word opens<br/>a <em>world to see.</em><svg className="title-swish" viewBox="0 0 295 15" aria-hidden="true"><path d="M3 10Q125-2 292 6"/></svg></h1><p className="hero-chinese" lang="zh-Hans">看图 · 听音 · 学华文</p><p className="hero-description">Discover Mandarin through pictures.<br/>For curious minds, of every age.</p><div className="hero-benefits"><span><span className="benefit-icon"><BookOpen size={15}/></span> See it</span><span><span className="benefit-icon"><AudioLines size={16}/></span> Hear it</span><span><span className="benefit-icon"><Sparkles size={15}/></span> Remember it</span></div></div>
      <div className="hero-art" aria-label="Discover Mandarin through photographs"><span className="hero-doodle doodle-one">✧</span><span className="hero-doodle doodle-two">✳</span><span className="art-orbit"/><button className="hero-photo hero-cat" onClick={() => onOpen(byId.get('猫')!)}><Photo photo={localPhoto('cat', 'A curious cat — 猫')!} eager/><span className="hero-photo-label"><strong lang="zh-Hans">猫</strong><span>māo <small>cat</small></span><ArrowUpRight size={18}/></span></button><button className="hero-photo hero-apple" onClick={() => onOpen(byId.get('苹果')!)}><Photo photo={localPhoto('apple', 'Fresh apples — 苹果')!} eager/><span className="hero-photo-label"><strong lang="zh-Hans">苹果</strong><span>píng guǒ <small>apple</small></span><ArrowUpRight size={18}/></span></button><button className="hero-photo hero-plane" onClick={() => onOpen(byId.get('飞机')!)}><Photo photo={localPhoto('airplane', 'An airplane — 飞机')!} eager/><span className="hero-photo-label"><strong lang="zh-Hans">飞机</strong><span>fēi jī <small>airplane</small></span><ArrowUpRight size={18}/></span></button><div className="floating-note"><span>你好！</span><small>A new way to say hello.</small></div><span className="art-caption">Real pictures. Real connections.</span></div>
    </section>
    <section className="home-search"><SearchBar large onSearch={onSearch} recent={recent}/><div className="search-examples"><span>One word. Four ways to find it.</span>{['苹果', 'píng guǒ', 'apple', 'epal'].map(q => <button key={q} onClick={() => onSearch(q)}>{q}<ArrowUpRight size={12}/></button>)}</div></section>
    <section className="explore-section" id="explore"><div className="section-heading"><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h2>Explore by pictures <span lang="zh-Hans">看图学词</span></h2></div><span className="section-caption">Big discoveries start with a little look.</span></div><div className="category-grid">{categories.map(([name, chinese, id, description, color]) => { const word = byId.get(id)!; return <button key={name} className={`category-card ${color}`} onClick={() => onCategory(name)} aria-label={`Explore ${name}`}><div className="category-image"><WordThumbnail word={word}/><span className="category-arrow"><ArrowUpRight size={18}/></span></div><div className="category-body"><strong lang="zh-Hans">{chinese}</strong><span>{name}</span><small>{description}</small></div></button>; })}</div></section>
    <section className="daily-word"><div className="daily-picture"><Photo photo={localPhoto(today.photo!, today.senses[0].english)!}/><span className="daily-badge"><Sparkles size={14}/> WORD OF THE DAY</span></div><div className="daily-copy"><span className="eyebrow">今日词语 · A NEW WORD, A NEW DISCOVERY</span><div className="daily-title"><h2 lang="zh-Hans">{today.simplified}</h2><PronunciationButton text={today.simplified} compact/></div><p className="daily-pinyin">{today.pinyin}</p><p className="daily-meaning">{today.senses[0].english.split(';')[0]} <span>· {today.senses[0].malay}</span></p><p className="daily-example" lang="zh-Hans">{today.senses[0].examples[0].chinese}</p><p className="daily-translation">{today.senses[0].examples[0].english}</p><button className="primary-button" onClick={() => onOpen(today)}>Meet this word <ArrowRight size={17}/></button></div><div className="daily-decoration" aria-hidden="true">学<small>one word<br/>at a time.</small></div></section>
    <section className="popular-section"><div className="section-heading"><div><span className="eyebrow">LITTLE WORDS, EVERYDAY WONDERS</span><h2>A good place to start <span lang="zh-Hans">热门词语</span></h2></div><button className="text-button" onClick={() => onCategory('All')}>Explore all words <ArrowRight size={17}/></button></div><div className="word-grid">{popular.map(word => <WordCard key={word.id} word={word} onOpen={onOpen} saved={saved.includes(word.id)} onSave={onSave}/>)}</div></section>
    <section className="bottom-note"><span className="note-icon"><Globe2 size={30}/></span><div><h3>A shared world. More ways to understand it.</h3><p>Chinese, English and Bahasa Melayu — learning feels closer when languages come together.</p></div><span lang="zh-Hans">一起学，一起成长。</span></section>
  </>;
}
