import { useEffect, useRef, useState } from 'react';
import { ArrowUpLeft, Clock3, Search, X } from 'lucide-react';
import { coreIndex } from '../lib/search';
import type { Word } from '../types';
export function SearchBar({ onSearch, recent, initial = '', large = false }: { onSearch: (q: string) => void; recent: string[]; initial?: string; large?: boolean }) {
  const [query, setQuery] = useState(initial); const [open, setOpen] = useState(false); const [suggestions, setSuggestions] = useState<Word[]>([]);
  const [active, setActive] = useState(-1); const composing = useRef(false); const input = useRef<HTMLInputElement>(null); const wrapper = useRef<HTMLDivElement>(null);
  useEffect(() => { setQuery(initial); }, [initial]);
  useEffect(() => { if (composing.current) return; const timer = setTimeout(() => setSuggestions(query.trim() ? coreIndex.search(query, 5) : []), 150); return () => clearTimeout(timer); }, [query]);
  useEffect(() => { const close = (e: PointerEvent) => { if (!wrapper.current?.contains(e.target as Node)) setOpen(false); }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, []);
  const entries = query.trim() ? suggestions.map(w => ({ value: w.simplified, detail: `${w.pinyin} · ${w.senses[0].english}` })) : recent.slice(0, 4).map(q => ({ value: q, detail: 'Recent search' }));
  function submit(value: string) { if (!value.trim() || composing.current) return; setQuery(value); setOpen(false); setActive(-1); onSearch(value.trim()); }
  return <div className={`search-wrapper ${large ? 'large' : ''}`} ref={wrapper}><form className="search-bar" role="search" onSubmit={e => { e.preventDefault(); submit(active >= 0 ? entries[active].value : query); }}>
    <Search size={23} className="search-icon"/><input ref={input} aria-label="Search Mandarin, pinyin, English or Bahasa Melayu" role="combobox" aria-expanded={open && entries.length > 0} aria-controls="search-suggestions" aria-autocomplete="list" aria-activedescendant={active >= 0 ? `suggestion-${active}` : undefined} value={query} maxLength={100} placeholder="搜索华文字、拼音、English 或 Bahasa Melayu…" autoComplete="off" onFocus={() => setOpen(true)} onChange={e => { setQuery(e.target.value); setActive(-1); if (!composing.current) setOpen(true); }} onCompositionStart={() => { composing.current = true; setOpen(false); }} onCompositionEnd={e => { composing.current = false; setQuery(e.currentTarget.value); setSuggestions(coreIndex.search(e.currentTarget.value, 5)); setOpen(true); }} onKeyDown={e => { if (composing.current || e.nativeEvent.isComposing) { if (e.key === 'Enter') e.preventDefault(); return; } if (e.key === 'Escape') setOpen(false); if (e.key === 'ArrowDown') { e.preventDefault(); setOpen(true); setActive(a => Math.min(a + 1, entries.length - 1)); } if (e.key === 'ArrowUp') { e.preventDefault(); setActive(a => Math.max(-1, a - 1)); } }}/>
    {query && <button type="button" className="clear-search" aria-label="Clear search" onClick={() => { setQuery(''); setSuggestions([]); setActive(-1); input.current?.focus(); }}><X size={18}/></button>}<button type="submit" className="search-submit"><span>Find a word</span><Search size={19}/></button>
  </form>{open && entries.length > 0 && <ul className="search-suggestions" id="search-suggestions" role="listbox" aria-label="Word suggestions">{entries.map((entry, i) => <li role="option" id={`suggestion-${i}`} aria-selected={active === i} key={entry.value}><button type="button" tabIndex={-1} onMouseDown={e => e.preventDefault()} onClick={() => submit(entry.value)}>{!query && <Clock3 size={16}/>}<strong lang="zh-Hans">{entry.value}</strong><span>{entry.detail}</span><ArrowUpLeft size={17}/></button></li>)}</ul>}</div>;
}
