// Native Node entrypoint. The deterministic server bundle is checked in and
// regenerated by npm run build; no extensionless TypeScript imports at runtime.
let service;
export default async function handler(req, res) {
  let run;
  try {
    service ??= import('../server/image-service.mjs');
    run = (await service).default;
  } catch {
    service = undefined;
    // Never log raw import errors: paths, environment values, or provider URLs
    // can be embedded in their messages. Keep an actionable server-side code.
    console.error('[images] image_service_initialization_failed');
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.end(JSON.stringify({ error: 'Images unavailable', diagnostic: 'image_service_initialization_failed' }));
    return;
  }
  return run(req, res);
}
